-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
vim.opt.clipboard = "unnamedplus"
-- vim.g.clipboard = {
--   name = "OSC 52",
--   copy = {
--     ["+"] = require("vim.ui.clipboard.osc52").copy("+"),
--     ["*"] = require("vim.ui.clipboard.osc52").copy("*"),
--   },
--   paste = {
--     ["+"] = require("vim.ui.clipboard.osc52").paste("+"),
--     ["*"] = require("vim.ui.clipboard.osc52").paste("*"),
--   },
-- }
vim.diagnostic.enable(false)
-- Force Neovim to use the Windows clipboard in WSL
-- if vim.fn.has("wsl") == 1 then
--   vim.g.clipboard = {
--     name = "WslClipboard",
--     copy = {
--       ["+"] = "clip.exe",
--       ["*"] = "clip.exe",
--     },
--     paste = {
--       ["+"] = 'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
--       ["*"] = 'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
--     },
--     cache_enabled = 0,
--   }
-- end
-- vim.filetype.add({
--   extension = {
--     templ = "templ",
--   },
-- })
-- if vim.fn.executable("/mnt/c/Windows/System32/clip.exe") == 1 then
--   vim.api.nvim_create_autocmd("TextYankPost", {
--     group = vim.api.nvim_create_augroup("WSLClipboard", { clear = true }),
--     callback = function()
--       if vim.v.event.operator == "y" then
--         vim.fn.system("/mnt/c/Windows/System32/clip.exe", vim.fn.getreg('"'))
--       end
--     end,
--   })
-- end
